# Generated by Django 2.2.5 on 2020-07-19 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Care', '0004_auto_20200719_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
