# Generated by Django 2.2.5 on 2020-07-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_auto_20200718_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CG', 'Care Giver'), ('CT', 'Care Taker')], default='CG', max_length=2),
            preserve_default=False,
        ),
    ]
