# Generated by Django 2.2.5 on 2020-07-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CG', 'Care Giver'), ('CT', 'Care Taker')], default='CG', max_length=2),
        ),
    ]
