# Generated by Django 2.2.5 on 2020-07-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Care', '0005_auto_20200719_1700'),
        ('useraccount', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
