# Generated by Django 2.2.5 on 2020-07-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_auto_20200719_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fees',
        ),
    ]
