# Generated by Django 2.2.5 on 2020-07-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_remove_user_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fees',
            field=models.IntegerField(blank=True, default=2000),
            preserve_default=False,
        ),
    ]
