# Generated by Django 2.2.5 on 2020-07-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_user_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
