# Generated by Django 2.2.5 on 2020-07-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0012_gig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gig',
        ),
    ]
