# Generated by Django 2.2.5 on 2020-07-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0015_addfriend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfriend',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], default='send', max_length=8),
        ),
    ]
