# Generated by Django 2.2.5 on 2020-07-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0019_auto_20200722_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CG', 'Care Giver'), ('CT', 'Care Reciever')], default='CG', max_length=2),
        ),
    ]
